import { Model } from 'mongoose';

export type IUser = {
  first_name?: string;
  last_name?: string;
  middle_name?: string;
  date_of_birth?: Date;
  gender?: string;
  employment_status?: string;
  flat_number?: string;
  building_name?: string;
  street?: string;
  branch?: string;
  city?: string;
  landmark?: string;
  country?: string;
  state?: string;
  postal_code?: number;
  basic_details?: Record<string, unknown>;
  permanent_address?: Record<string, unknown>;
  phone_number?: string;
  other_phone_number?: string;
  personal_email?: string;
  office_email?: string;
  communication_details?: Record<string, unknown>;
  bank_name?: string;
  account_number?: number;
  ifsc_code?: string;
  bank_details?: Record<string, unknown>;
  level?: string;
  designation?: string;
  department?: string;
  team?: string;
  role?: string;
  manager_id?: string;
  date_of_joining?: Date;
  uan_number?: string;
  job_details?: Record<string, unknown>;
  emergency_contact?: Record<string, unknown>;
  emergency_contact_details?: Record<string, unknown>;
  employee_code?: string;
  contract_date?: Date;
  user_type?: 'super_admin' | 'hr' | 'employee' | 'admin' | 'payslipUser';
  other?: Record<string, unknown>;
  hr_only?: Record<string, unknown>;
  organization_id?: string;
  password?: string;
  profile_picture?: string;
  user_id?: string;
  status: 'Deleted' | 'Disabled' | 'Active';
  last_login_time?: Date;
  last_online_time?: Date;
  is_logged_in?: boolean;
  is_online?: boolean;
  is_profile_completed?: boolean;
  is_password_reset?: boolean;
  is_password_created_by_user?: boolean;
  height?: string;
  weight?: string;
  steps_everyday_goal?: number;
  esic_number?: string;
  pf_number?: string;
};

export type UserModel = Model<IUser, Record<string, unknown>>;
